projects/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.ProjectListView.as_view(), name='index'),
    path('create/', views.ProjectCreateView.as_view(), name='create'),
    path('<int:project_id>/', views.ProjectView.as_view(), name='project-detail'),
    path('<int:project_id>/delete/', views.ProjectDeleteView.as_view(), name='delete'),
    path('<int:project_id>/members/create/', views.ProjectMemberCreateView.as_view(), name='create-member'),
    path('<int:project_id>/members/', views.ProjectMembersView.as_view(), name='project-members'),
    path('<int:project_id>/members/<int:member_id>/edit/', views.ProjectMemberEditView.as_view(), name='project-member-edit'),
    path('<int:project_id>/backlog/', views.ProductBacklogView.as_view(), name='project-backlog'),
    path('<int:project_id>/backlog/create/', views.ProductBacklogCreateView.as_view(), name='project-backlog-create'),
    path('<int:project_id>/backlog/<int:us_id>/edit/', views.ProductBacklogEditView.as_view(), name='project-backlog-edit'),
    path('<int:project_id>/backlog/<int:us_id>/', views.ProductBacklogDetailView.as_view(), name='project-backlog-detail'),
    path('<int:project_id>/backlog/<int:us_id>/cancel/', views.ProductBacklogCancelView.as_view(), name='backlog-cancel'),
    path('<int:project_id>/backlog/<int:us_id>/comments/create', views.ProductBacklogCreateCommentView.as_view(), name='comment-create'),
    path('<int:project_id>/backlog/<int:us_id>/tasks/create', views.ProductBacklogCreateTaskView.as_view(), name='task-create'),
    path('<int:project_id>/backlog/<int:us_id>/comments/<int:comment_id>/delete', views.ProductBacklogDeleteCommentView.as_view(), name='comment-delete'),
    path('<int:project_id>/velocity', views.VelocityChartView.as_view(), name='velocity'),
    path('<int:project_id>/finish/', views.ProjectFinishView.as_view(), name='finish'),

    #Attachments
    path('<int:project_id>/backlog/<int:us_id>/attachments/<int:attachment_id>', views.UserStoryAttachmentDownloadView.as_view(), name='us-attachment-download'),
    path('<int:project_id>/backlog/<int:us_id>/attachments/create', views.ProductBacklogCreateAttachmentView.as_view(), name='us-attachment-create'),
    path('<int:project_id>/backlog/<int:us_id>/attachments/<int:attachment_id>/delete', views.ProductBacklogDeleteAttachmentView.as_view(), name='us-attachment-delete'),

    #User story type
    path('<int:project_id>/user-story-type/', views.UserStoryTypeListView.as_view(), name='user-story-type-list'),
    path('<int:project_id>/user-story-type/create/', views.UserStoryTypeCreateView.as_view(), name='user-story-type-create'),
    path('<int:project_id>/user-story-type/<int:id>/edit/', views.UserStoryTypeEditView.as_view(), name='user-story-type-edit'),
    path('<int:project_id>/user-story-type/<int:id>/delete/', views.UserStoryTypeDeleteView.as_view(), name='user-story-type-delete'),
    path('<int:project_id>/user-story-type/import/', views.UserStoryTypeImportView1.as_view(), name='user-story-type-import1'),
    path('<int:project_id>/user-story-type/import/<int:from_project_id>/', views.UserStoryTypeImportView2.as_view(), name='user-story-type-import2'),

    #Role
    path('<int:project_id>/roles/create/', views.ProjectRoleCreateView.as_view(), name='create-role'), #esto debe arreglar ale
    path('<int:project_id>/roles/', views.ProjectRoleView.as_view(), name='index-roles'), #el index de roles dedl proyecto, el id es del proyecto
    path('<int:project_id>/roles/<int:role_id>/edit/', views.ProjectRoleEditView.as_view(), name='edit-role'), #esto debe arreglar ale
    path('<int:project_id>/roles/<int:role_id>/delete/', views.ProjectRoleDeleteView.as_view(), name='delete-role'),
    path('<int:project_id>/roles/import/', views.RoleImportView1.as_view(), name='import-role1'),
    path('<int:project_id>/roles/import/<int:from_project_id>/', views.RoleImportView2.as_view(), name='import-role2'),

    #Sprint
    path('<int:project_id>/sprints/', include(('sprints.urls', 'sprints'))),

    # Active board
    path('<int:project_id>/board/', include(('sprints.urls_board', 'board'))),

    # API
    path('<int:project_id>/user-stories/<int:us_id>/', views.UserStoryEditApiView.as_view()),

    # User Stories
    path('<int:project_id>/backlog/<int:user_story_id>/history/', include(('user_stories.urls', 'history'))),

    # Holidays
    path('<int:project_id>/holidays/', views.ProjectHolidayView.as_view(), name='index-holidays'), #el index de feriados del proyecto, el id es del proyecto
    path('<int:project_id>/holidays/create/', views.ProjectCreateHolidayView.as_view(), name='create-holiday'), #el index de feriados del proyecto, el id es del proyecto
    path('<int:project_id>/holidays/delete/<int:project_holiday_id>/', views.ProjectDeleteHolidayView.as_view(), name='delete-holiday'), #el index de feriados del proyecto, el id es del proyecto
]

sga/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views
from users import views as views_users

handler404 = 'sga.views.custom_404'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', views.login, name='login'),
    path('accounts/', include('allauth.urls')),
    path('profile/', views_users.ProfileView.as_view(), name='profile'),
    path('', views.index, name='index'),

    path('projects/', include(('projects.urls', 'projects'))),
    path('users/', include(('users.urls', 'users'))),
    path('user_stories/', include(('user_stories.urls', 'user_stories'))),
    path('notifications/', include(('notifications.urls', 'notifications'))),

    ### SOLO PARA LOGEAR CON USUARIOS DE PRUEBA ###
    path('accounts/login-email/', views.login_email, name='login-email'),
]

sprints/views.py
from django.views.generic import ListView, DetailView, FormView
from django.views import View
from django.contrib import messages
from django.urls import reverse
from django.shortcuts import redirect, render
from django.forms.models import model_to_dict
from projects.mixin import *
from projects.models import UserStoryType, ProjectStatus
from projects.usecase import ProjectUseCase
from users.models import CustomUser
from sprints.forms import SprintCreateForm, SprintMemberCreateForm, SprintMemberEditForm, SprintStartForm, AssignSprintMemberForm,FormCreateComment, SprintMemberSwitchForm
from sprints.models import Sprint, SprintMember
from sprints.usecase import *
from sprints.mixin import *
from user_stories.usecase import UserStoriesUseCase
from user_stories.models import UserStory, UserStoryTask
from sga.mixin import CustomLoginMixin
import copy
from datetime import date, timedelta
from notifications.usecase import NotificationUseCase

class SprintListView(CustomLoginMixin, ProjectAccessMixin, ListView):
    """
    Vista que lista los sprints de un proyecto
    """
    model = Sprint
    template_name = 'sprints/index.html'

    def get_queryset(self):
        return self.model.objects.filter(project_id=self.kwargs.get('project_id'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Agregamos el id del proyecto en el contexto para ser usado en el template
        context['project_id'] = self.kwargs.get('project_id')
        context['backpage'] = reverse('projects:project-detail', kwargs={'project_id': context['project_id']})

        return context

class SprintCreateView(CustomLoginMixin, ProjectPermissionMixin, ProjectStatusMixin, FormView):
    """
    Vista para crear un nuevo sprint
    """
    permissions = ['ABM Sprint']
    roles = ['Scrum Master']

    form_class = SprintCreateForm
    template_name = 'sprints/create.html'

    def get(self, request, project_id, **kwargs):
        # Si el proyecto no esta en progreso, no se puede crear un sprint
        if not ProjectUseCase.get_project_status(project_id) == ProjectStatus.IN_PROGRESS:
            messages.warning(request, 'El proyecto aun no fue iniciado')
            return redirect(reverse('projects:sprints:index', kwargs={'project_id': project_id}))
        # Si ya existe un sprint en planeacion, no se puede crear otro
        if SprintUseCase.exists_created_sprint(project_id):
            messages.warning(request, 'Ya existe un sprint en planeación')
            return redirect(reverse('projects:sprints:index', kwargs={'project_id': project_id}))
        # Si no existe US en el backlog, no se puede crear un sprint
        if not ProjectUseCase.user_stories_in_progress_by_project_exists(project_id):
            messages.warning(request, 'No existen historias de usuario en el Backlog para crear un sprint')
            return redirect(reverse('projects:sprints:index', kwargs={'project_id': project_id}))
        return super().get(request, project_id, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['project_id'] = self.kwargs.get('project_id')
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Agregamos el id del proyecto en el contexto para ser usado en el template
        context['project_id'] = self.kwargs.get('project_id')
        context['backpage'] = reverse('projects:sprints:index', kwargs={'project_id': context['project_id']})
        return context

    def form_valid(self, form):
        # Creamos el sprint
        data = form.cleaned_data
        project_id = self.kwargs.get('project_id')
        SprintUseCase.create_sprint(project_id, **data)
        messages.success(self.request, 'Sprint creado con éxito')
        return super().form_valid(form)

    def get_success_url(self):
        namespace = 'projects:sprints:index'
        return reverse(namespace, kwargs={'project_id': self.kwargs.get('project_id')})

class SprintView(CustomLoginMixin, SprintAccessMixin, DetailView):
    """
    Vista que lista los detalles de un sprint
    """
    model = Sprint
    template_name = 'sprints/detail.html'
    # Indicamos el pk del objeto
    pk_url_kwarg = 'sprint_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Agregamos el id del proyecto en el contexto para ser usado en el template
        project_id = self.kwargs.get('project_id')
        context['project_id'] = project_id
        context['backpage'] = reverse('projects:sprints:index', kwargs={'project_id': context['project_id']})
        if self.is_scrum_master:
            context['modify_sprint_status'] = True
        else:
            context['modify_sprint_status'] = ProjectUseCase.member_has_permissions(self.request.user.id, project_id, ["ABM Sprint"])
        return context

    def post(self, request, project_id, sprint_id):
        sprint = super().get_object()
        try:
            if sprint.status == "PLANNED":
                SprintUseCase.start_sprint(sprint)
                NotificationUseCase.notify_start_sprint(request.user, project_id, sprint)
                messages.success(request, f"Sprint iniciado correctamente")
            elif sprint.status == "IN_PROGRESS":
                return redirect(reverse("projects:sprints:finish", kwargs={"project_id": project_id, "sprint_id": sprint_id}))
        except CustomError as e:
            messages.warning(request, e)
        return redirect(reverse('projects:sprints:detail', kwargs={'project_id': project_id, 'sprint_id': sprint_id}))

class SprintFinishView(CustomLoginMixin, SprintPermissionMixin, SprintStatusMixin, View):
    """
    Vista para finalizar un sprint
    """
    permissions = ["ABM Sprint"]
    roles = ["Scrum Master"]

    def get(self, request, project_id, sprint_id):
        sprint = Sprint.objects.get(id=sprint_id)
        us = UserStory.objects.filter(sprint_id=sprint_id)
        us_type = UserStoryType.objects.filter(project_id=project_id)
        us_show = []
        for u in us:
            if len(u.us_type.columns) - 1 == u.column:
                us_show.append(u)
        context = { "us": us_show }
        return render(request, 'sprints/finish.html', context)

    def post(self, request, project_id, sprint_id):
        sprint = Sprint.objects.get(id=sprint_id)
        SprintUseCase.finish_sprint(sprint, request.user, self.kwargs.get('project_id'))
        NotificationUseCase.notify_finish_sprint(request.user, project_id, sprint)
        messages.success(request, f"Sprint finalizado correctamente, prioridades y estados de las historias de usuario actualizadas")
        return redirect(reverse('projects:sprints:detail', kwargs={'project_id': project_id, 'sprint_id': sprint_id}))

class SprintMemberCreateView(CustomLoginMixin, SprintPermissionMixin, SprintStatusMixin, FormView):
    """
    Vista para crear miembro de un sprint
    """
    permissions = ['ABM Miembro Sprint']
    roles = ['Scrum Master']
    special_status = "IN_PROGRESS"
    special_message = "No se puede agregar miembros a un sprint en progreso"

    template_name = 'sprint-members/create.html'
    form_class = SprintMemberCreateForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['project_id'] = self.kwargs.get('project_id')
        kwargs['sprint_id'] = self.kwargs.get('sprint_id')
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Agregamos el id del proyecto en el contexto para ser usado en el template
        context['project_id'] = self.kwargs.get('project_id')
        context['backpage'] = reverse('projects:sprints:index', kwargs={'project_id': context['project_id']})
        return context

    def get_success_url(self):
        return reverse('projects:sprints:member-list', kwargs={
            'project_id': self.kwargs.get('project_id'),
            'sprint_id': self.kwargs.get('sprint_id'),
        })

    def form_valid(self, form):
        """
        Metodo que se ejecuta si el formulario es valido
        """
        data = form.cleaned_data
        sprint_id = self.kwargs.get('sprint_id')
        sprint_member = SprintUseCase.add_sprint_member(
            sprint_id=sprint_id,
            **data
        )
        NotificationUseCase.notify_add_member_to_sprint(sprint_member)
        messages.success(self.request, f"Usuario <strong>{data['user']}</strong> agregado al sprint correctamente")
        return super().form_valid(form)

class SprintMemberSwitchView(CustomLoginMixin, SprintPermissionMixin, SprintStatusMixin, FormView):
    """
    Vista para cambiar un miembro del sprint por otro usuario del proyecto
    """
    permissions = ['ABM Miembro Sprint']
    roles = ['Scrum Master']

    template_name = 'sprint-members/switch.html'
    form_class = SprintMemberSwitchForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['project_id'] = self.kwargs.get('project_id')
        kwargs['sprint_id'] = self.kwargs.get('sprint_id')
        sprint_member = SprintMember.objects.get(id=self.kwargs.get('sprint_member_id'))
        kwargs['initial'] = {
            'workload': sprint_member.workload,
            'user': sprint_member.user.email
        }
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        sprint_member = SprintMember.objects.get(id=self.kwargs.get('sprint_member_id'))
        context['sprint_member'] = sprint_member
        context['project_id'] = self.kwargs.get('project_id')
        context['backpage'] = reverse('projects:sprints:index', kwargs={'project_id': context['project_id']})
        return context

    def get_success_url(self):
        return reverse('projects:sprints:member-list', kwargs={

projects/templates/roles/create.html
{% extends 'sga/layout/base_generic.html'%}
{% load static %}
{% block head %}
  <script src="{% static 'sga/js/checkAll.js' %}"></script>
{% endblock %}
{% block content %}
<b></b>
	<h1>Crear Rol</h1>

	<form method="post" class="form row g-3">
		{% csrf_token %}
		{% for field in form %}
      {% include "utils/form_field.html" with field=field %}
    {% endfor %}

    {% for error in form.non_field_errors %}
      <div class="alert alert-danger">{{ error }}</div>
    {% endfor %}
		<input type="submit" value="Guardar">
	</form>
{% endblock %}

projects/templates/roles/delete.html
{% extends 'sga/layout/base_generic.html'%}
{% block content %}
<b></b>
	<h1>Borrar Rol</h1>
	{% include 'utils/messages.html'%}
	<form method="post" class="form row g-3">
		{% csrf_token %}
		{% for field in form %}
      {% include "utils/form_field_no_edit.html" with field=field %}
    {% endfor %}

    {% for error in form.non_field_errors %}
      <div class="alert alert-danger">{{ error }}</div>
    {% endfor %}
		<input type="submit" value="Borrar">
	</form>
{% endblock %}

projects/templates/roles/edit.html
{% extends 'sga/layout/base_generic.html'%}
{% load static %}
{% block head %}
  <script src="{% static 'sga/js/checkAll.js' %}"></script>
{% endblock %}
{% block content %}
<b></b>
	<h1>Editar Rol</h1>
	{% include 'utils/messages.html'%}
	<form method="post" class="form row g-3">
		{% csrf_token %}
		{% for field in form %}
      {% include "utils/form_field.html" with field=field %}
    {% endfor %}

    {% for error in form.non_field_errors %}
      <div class="alert alert-danger">{{ error }}</div>
    {% endfor %}
		<input type="submit" value="Guardar">
	</form>
{% endblock %}

projects/templates/roles/import1.html
{% extends 'sga/layout/base_generic.html'%}
{% block content %}
<b></b>

	<h1>Importar Rol</h1>
	{% include 'utils/messages.html'%}
	<form method="post" class="form row g-3">
		{% csrf_token %}
		{% for field in form %}
      {% include "utils/form_field.html" with field=field %}
    {% endfor %}

    {% for error in form.non_field_errors %}
      <div class="alert alert-danger">{{ error }}</div>
    {% endfor %}
		<input type="submit" value="Siguiente">
	</form>
{% endblock %}

projects/templates/roles/import2.html
{% extends 'sga/layout/base_generic.html'%}
{% load static %}
{% block head %}
  <script src="{% static 'sga/js/checkAll.js' %}"></script>
{% endblock %}

{% block content %}
<b></b>
	<h1>Importar Rol</h1>
	{% include 'utils/messages.html'%}
	<form  method="post" class="form row g-3">
		{% csrf_token %}
		<table class="table">
			<thead>
				<tr>
					<th scope="col"><input type="checkbox" id="check-all"></th>
					<th scope="col">Rol</th>
					<th scope="col">Permisos</th>
				</tr>
			</thead>
			<tbody>
				{% for role in roles %}
				<tr>
					<td>
					<input type="checkbox" name="roles" value="{{role.role.id}}"
					{%if role.role.id in checked%} checked {%endif%}>
					</td>
					<td>{{ role.role.name }}</td>
					<td>
					{% for perm in role.permissions %}
						<p>{{ perm.name }}, </p>
					{% endfor %}
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		<input type="submit" value="Guardar">
	</form>
{% endblock %}

projects/templates/roles/index.html
{% extends 'sga/layout/base_generic.html'%}
{% block content %}
  <h1>Roles</h1>
  <a href="{% url 'projects:create-role' project_id=project_id %}" class="btn btn-labeled btn-info">
    <span class="btn-label"><i class="fa fa-plus"></i></span>Crear Rol
  </a>
  <a href="{% url 'projects:import-role1' project_id=project_id %}" class="btn btn-labeled btn-info">
    <span class="btn-label"><i class="fa fa-file-import"></i></span>Importar Rol
  </a>
  {% include 'utils/messages.html'%}
  <table class="table-custom">
    <thead>
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Descripcion</th>
        <th scope="col">Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% for role in roles %}
      <tr height="60px">
        <td>{{ role.name }}</td>
        <td>{{ role.description }}</td>
        <td>
          <a href="{% url 'projects:edit-role' project_id=project_id role_id=role.id %}" class="btn" title="Editar rol">
            <span class="btn-label"><i class="fa fa-pencil"></i></span>
          </a>
          <a href="{% url 'projects:delete-role' project_id=project_id role_id=role.id %}" class="btn" title="Eliminar rol">
            <span class="btn-label"><i class="fa fa-trash"></i></span>
          </a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}