sga/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views
from users import views as views_users

handler404 = 'sga.views.custom_404'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', views.login, name='login'),
    path('accounts/', include('allauth.urls')),
    path('profile/', views_users.ProfileView.as_view(), name='profile'),
    path('', views.index, name='index'),

    path('projects/', include(('projects.urls', 'projects'))),
    path('users/', include(('users.urls', 'users'))),
    path('user_stories/', include(('user_stories.urls', 'user_stories'))),
    path('notifications/', include(('notifications.urls', 'notifications'))),

    ### SOLO PARA LOGEAR CON USUARIOS DE PRUEBA ###
    path('accounts/login-email/', views.login_email, name='login-email'),
]

sga/models.py
from django.db import models

sga/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache

from django.dispatch.dispatcher import receiver
from django.contrib.auth.signals import user_logged_out
from django.contrib.auth.signals import user_logged_in
from django.contrib import messages

from projects.models import Project
from projects.usecase import ProjectUseCase
from sprints.usecase import SprintUseCase

@receiver(user_logged_in)
def user_logged_in_(request, **kwargs):
    """
    Limpia los mensajes antes de que el usuario inicie sesión
    """
    list(messages.get_messages(request))
    print("user_logged_in")

@receiver(user_logged_out)
def user_logged_out(request, **kwargs):
    """
    Limpia los mensajes immediatamente después de que un usuario cierra sesion
    """
    list(messages.get_messages(request))
    print("user_logged_out")

@never_cache
@login_required()
def index(request):
    if request.user.is_authenticated:
        projects = ProjectUseCase.get_projects_and_sprint_active(request.user)
        context = {"projects": projects}
    return render(request, 'sga/index.html', context)

@never_cache
def login(request):
    if request.user.is_authenticated:
        return redirect("/")
    return render(request, 'account/login.html')

def custom_404(request, exception):
    messages.warning(request, "Página no encontrada")
    return redirect("/")

### SOLO PARA LOGEAR CON USUARIOS DE PRUEBA ###
from django.shortcuts import reverse
from django.contrib.auth import authenticate
from django.contrib.auth import login as django_login
from users.models import CustomUser
import os

@never_cache
def login_email(request):
    if request.user.is_authenticated:
        return redirect("/")
    if os.environ.get("DEBUG") == "0":
        return redirect(reverse("login"))
    email=request.POST.get("fname")
    try:
        user = CustomUser.objects.get(email=email)
        if not user.password:
            user.set_password("")
            user.save()
        auth_user = authenticate(email=email, password="")
        if auth_user:
            django_login(request, auth_user)
            return redirect("/")
    except:
        user = None
    return render(request, 'account/login_email.html')

sprints/views.py
from django.views.generic import ListView, DetailView, FormView
from django.views import View
from django.contrib import messages
from django.urls import reverse
from django.shortcuts import redirect, render
from django.forms.models import model_to_dict
from projects.mixin import *
from projects.models import UserStoryType, ProjectStatus
from projects.usecase import ProjectUseCase
from users.models import CustomUser
from sprints.forms import SprintCreateForm, SprintMemberCreateForm, SprintMemberEditForm, SprintStartForm, AssignSprintMemberForm,FormCreateComment, SprintMemberSwitchForm
from sprints.models import Sprint, SprintMember
from sprints.usecase import *
from sprints.mixin import *
from user_stories.usecase import UserStoriesUseCase
from user_stories.models import UserStory, UserStoryTask
from sga.mixin import CustomLoginMixin
import copy
from datetime import date, timedelta
from notifications.usecase import NotificationUseCase

class SprintListView(CustomLoginMixin, ProjectAccessMixin, ListView):
    """
    Vista que lista los sprints de un proyecto
    """
    model = Sprint
    template_name = 'sprints/index.html'

    def get_queryset(self):
        return self.model.objects.filter(project_id=self.kwargs.get('project_id'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Agregamos el id del proyecto en el contexto para ser usado en el template
        context['project_id'] = self.kwargs.get('project_id')
        context['backpage'] = reverse('projects:project-detail', kwargs={'project_id': context['project_id']})

        return context

class SprintCreateView(CustomLoginMixin, ProjectPermissionMixin, ProjectStatusMixin, FormView):
    """
    Vista para crear un nuevo sprint
    """
    permissions = ['ABM Sprint']
    roles = ['Scrum Master']

    form_class = SprintCreateForm
    template_name = 'sprints/create.html'

    def get(self, request, project_id, **kwargs):
        # Si el proyecto no esta en progreso, no se puede crear un sprint
        if not ProjectUseCase.get_project_status(project_id) == ProjectStatus.IN_PROGRESS:
            messages.warning(request, 'El proyecto aun no fue iniciado')
            return redirect(reverse('projects:sprints:index', kwargs={'project_id': project_id}))
        # Si ya existe un sprint en planeacion, no se puede crear otro
        if SprintUseCase.exists_created_sprint(project_id):
            messages.warning(request, 'Ya existe un sprint en planeación')
            return redirect(reverse('projects:sprints:index', kwargs={'project_id': project_id}))
        # Si no existe US en el backlog, no se puede crear un sprint
        if not ProjectUseCase.user_stories_in_progress_by_project_exists(project_id):
            messages.warning(request, 'No existen historias de usuario en el Backlog para crear un sprint')
            return redirect(reverse('projects:sprints:index', kwargs={'project_id': project_id}))
        return super().get(request, project_id, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['project_id'] = self.kwargs.get('project_id')
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Agregamos el id del proyecto en el contexto para ser usado en el template
        context['project_id'] = self.kwargs.get('project_id')
        context['backpage'] = reverse('projects:sprints:index', kwargs={'project_id': context['project_id']})
        return context

    def form_valid(self, form):
        # Creamos el sprint
        data = form.cleaned_data
        project_id = self.kwargs.get('project_id')
        SprintUseCase.create_sprint(project_id, **data)
        messages.success(self.request, 'Sprint creado con éxito')
        return super().form_valid(form)

    def get_success_url(self):
        namespace = 'projects:sprints:index'
        return reverse(namespace, kwargs={'project_id': self.kwargs.get('project_id')})

class SprintView(CustomLoginMixin, SprintAccessMixin, DetailView):
    """
    Vista que lista los detalles de un sprint
    """
    model = Sprint
    template_name = 'sprints/detail.html'
    # Indicamos el pk del objeto
    pk_url_kwarg = 'sprint_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Agregamos el id del proyecto en el contexto para ser usado en el template
        project_id = self.kwargs.get('project_id')
        context['project_id'] = project_id
        context['backpage'] = reverse('projects:sprints:index', kwargs={'project_id': context['project_id']})
        if self.is_scrum_master:
            context['modify_sprint_status'] = True
        else:
            context['modify_sprint_status'] = ProjectUseCase.member_has_permissions(self.request.user.id, project_id, ["ABM Sprint"])
        return context

    def post(self, request, project_id, sprint_id):
        sprint = super().get_object()
        try:
            if sprint.status == "PLANNED":
                SprintUseCase.start_sprint(sprint)
                NotificationUseCase.notify_start_sprint(request.user, project_id, sprint)
                messages.success(request, f"Sprint iniciado correctamente")
            elif sprint.status == "IN_PROGRESS":
                return redirect(reverse("projects:sprints:finish", kwargs={"project_id": project_id, "sprint_id": sprint_id}))
        except CustomError as e:
            messages.warning(request, e)
        return redirect(reverse('projects:sprints:detail', kwargs={'project_id': project_id, 'sprint_id': sprint_id}))

class SprintFinishView(CustomLoginMixin, SprintPermissionMixin, SprintStatusMixin, View):
    """
    Vista para finalizar un sprint
    """
    permissions = ["ABM Sprint"]
    roles = ["Scrum Master"]

    def get(self, request, project_id, sprint_id):
        sprint = Sprint.objects.get(id=sprint_id)
        us = UserStory.objects.filter(sprint_id=sprint_id)
        us_type = UserStoryType.objects.filter(project_id=project_id)
        us_show = []
        for u in us:
            if len(u.us_type.columns) - 1 == u.column:
                us_show.append(u)
        context = { "us": us_show }
        return render(request, 'sprints/finish.html', context)

    def post(self, request, project_id, sprint_id):
        sprint = Sprint.objects.get(id=sprint_id)
        SprintUseCase.finish_sprint(sprint, request.user, self.kwargs.get('project_id'))
        NotificationUseCase.notify_finish_sprint(request.user, project_id, sprint)
        messages.success(request, f"Sprint finalizado correctamente, prioridades y estados de las historias de usuario actualizadas")
        return redirect(reverse('projects:sprints:detail', kwargs={'project_id': project_id, 'sprint_id': sprint_id}))

class SprintMemberCreateView(CustomLoginMixin, SprintPermissionMixin, SprintStatusMixin, FormView):
    """
    Vista para crear miembro de un sprint
    """
    permissions = ['ABM Miembro Sprint']
    roles = ['Scrum Master']
    special_status = "IN_PROGRESS"
    special_message = "No se puede agregar miembros a un sprint en progreso"

    template_name = 'sprint-members/create.html'
    form_class = SprintMemberCreateForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['project_id'] = self.kwargs.get('project_id')
        kwargs['sprint_id'] = self.kwargs.get('sprint_id')
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Agregamos el id del proyecto en el contexto para ser usado en el template
        context['project_id'] = self.kwargs.get('project_id')
        context['backpage'] = reverse('projects:sprints:index', kwargs={'project_id': context['project_id']})
        return context

    def get_success_url(self):
        return reverse('projects:sprints:member-list', kwargs={
            'project_id': self.kwargs.get('project_id'),
            'sprint_id': self.kwargs.get('sprint_id'),
        })

    def form_valid(self, form):
        """
        Metodo que se ejecuta si el formulario es valido
        """
        data = form.cleaned_data
        sprint_id = self.kwargs.get('sprint_id')
        sprint_member = SprintUseCase.add_sprint_member(
            sprint_id=sprint_id,
            **data
        )
        NotificationUseCase.notify_add_member_to_sprint(sprint_member)
        messages.success(self.request, f"Usuario <strong>{data['user']}</strong> agregado al sprint correctamente")
        return super().form_valid(form)

class SprintMemberSwitchView(CustomLoginMixin, SprintPermissionMixin, SprintStatusMixin, FormView):
    """
    Vista para cambiar un miembro del sprint por otro usuario del proyecto
    """
    permissions = ['ABM Miembro Sprint']
    roles = ['Scrum Master']

    template_name = 'sprint-members/switch.html'
    form_class = SprintMemberSwitchForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['project_id'] = self.kwargs.get('project_id')
        kwargs['sprint_id'] = self.kwargs.get('sprint_id')
        sprint_member = SprintMember.objects.get(id=self.kwargs.get('sprint_member_id'))
        kwargs['initial'] = {
            'workload': sprint_member.workload,
            'user': sprint_member.user.email
        }
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        sprint_member = SprintMember.objects.get(id=self.kwargs.get('sprint_member_id'))
        context['sprint_member'] = sprint_member
        context['project_id'] = self.kwargs.get('project_id')
        context['backpage'] = reverse('projects:sprints:index', kwargs={'project_id': context['project_id']})
        return context

    def get_success_url(self):
        return reverse('projects:sprints:member-list', kwargs={

sga/templates/sga/layout/base_generic.html
{% load static %}
{% load sga_extras %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
      integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
      crossorigin="anonymous"
    ></script>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
      integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'sga/style.css' %}"
    />
    <title>{% block title %}SGA {% endblock %}</title>
    {% block head %}
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <main class="main">
      {% include "./sidebar.html"%}
      <div class="content">
        <div style="line-height:60%;"><br></div>
        {% block breadcrumb %}
          {% breadcrumb %}
        {% endblock %}
        {% block content %}
        {% endblock %}
      </div>
    </main>
  </body>
</html>

sga/templates/sga/layout/sidebar.html
{% load sga_extras %}

<div
  id="sidebar"
  class="d-flex flex-column flex-shrink-0 p-3 bg-light"
  style="width: 280px"
>
  <a
    href="{% url 'index' %}"
    class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none"
  >
    <svg class="bi pe-none" width="40" height="32">
      <use xlink:href="#bootstrap"></use>
    </svg>
    <span class="fs-4">SGA</span>
  </a>
  <hr />
  <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
      <a href="{% url 'index' %}" class="nav-link {% if '/' == request.path%} active {%else%} link-dark {%endif%}" >
        <i class="fa-solid fa-house"></i>
        Home
      </a>
    </li>
    {% if user.is_verified %}
      <li>
        <a href="{% url 'projects:index' %}" class="nav-link {% if 'project' in request.path%} active {%else%} link-dark {%endif%}">
          <i class="fa-solid fa-diagram-project"></i>
          Proyectos
        </a>
        {% get_path_param request "project_id" as project_id %}
        {% if project_id %}
          <div class="collapse show" id="home-collapse">
            <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
              <li>
                <a href="{% url 'projects:board:index' project_id=project_id%}"
                  class="nav-sub-link link-dark {% is_active request 'board'%}">
                  Tablero
                </a>
              </li>
              <li>
                <a href="{% url 'projects:user-story-type-list' project_id=project_id%}"
                  class="nav-sub-link link-dark {% is_active request 'user-story-type'%}">
                  Tipos Historia Usuario
                </a>
              </li>
              <li>
                <a href="{% url 'projects:index-roles' project_id=project_id%}"
                  class="nav-sub-link link-dark {% is_active request 'roles'%}">
                  Roles
                </a>
              </li>
              <li>
                <a href="{% url 'projects:project-members' project_id=project_id%}"
                  class="nav-sub-link link-dark {% is_active request 'projects/\d/members'%}">
                  Miembros
                </a>
              </li>
              <li>
                <a href="{% url 'projects:project-backlog' project_id=project_id%}"
                  class="nav-sub-link link-dark {% is_active request 'projects/\d/backlog'%}">
                  Product Backlog
                </a>
              </li>
              <li>
                <a href="{% url 'projects:sprints:index' project_id=project_id%}"
                  class="nav-sub-link link-dark {% is_active request 'sprints'%}">
                  Sprints
                </a>
              </li>
            </ul>
          </div>
        {% endif %}
      </li>
      {% if user.is_admin%}
        <li>
          <a href="{% url 'users:index' %}" class="nav-link {% if 'users' in request.path%} active {%else%} link-dark {%endif%}">
            <i class="fa-solid fa-circle-user"></i>
            Usuarios
          </a>
        </li>
      {% endif %}
      <li>
        <a href="{% url 'notifications:index' %}" class="nav-link {% if 'notifications' in request.path%} active {%else%} link-dark {%endif%} nav-notification">
          <i class="fa-solid fa-bell">
          </i>
          {% if user.unread_notifications > 0 %}
            <span class="notification-badge badge bg-danger rounded-pill">{{ user.unread_notifications }}</span>
          {% endif %}
          Notificaciones
        </a>
      </li>
    {% endif %}
  </ul>
  {% if backpage %}
    <ul class="nav">
    <li>
      <a href="{{ backpage }}" class="nav-link link-dark">
        <i class="fa-solid fa-left-long"></i>
        Volver
      </a>
    </li>
  {% endif %}
</ul>
  <hr />
  <div class="dropdown">
    <a
      href="#"
      class="d-flex align-items-center link-dark text-decoration-none dropdown-toggle"
      data-bs-toggle="dropdown"
      aria-expanded="false"
    >
      <img
        src="{{user.picture}}"
        alt=""
        width="32"
        height="32"
        class="rounded-circle"
      />
      <strong>{{user.first_name}}</strong>
    </a>
    <ul class="dropdown-menu text-small shadow">
      <li><a class="dropdown-item" href="{% url 'profile' %}">Perfil</a></li>
      <li><hr class="dropdown-divider" /></li>
      <li>
        <a class="dropdown-item" href="/accounts/logout">Cerrar sesión</a>
      </li>
    </ul>
  </div>
</div>